#!/usr/bin/env python

from glob import glob
import os
import sys
from subprocess import check_call


# Load modules from $CHARM_DIR/lib
sys.path.append('lib')

# bootstrap wheelhouse
if os.path.exists('wheelhouse'):
    check_call(['pip', 'install', '--no-index'] + glob('wheelhouse/*'))


# This will load and run the appropriate @hook and other decorated
# handlers from $CHARM_DIR/reactive, $CHARM_DIR/hooks/reactive,
# and $CHARM_DIR/hooks/relations.
#
# See https://jujucharms.com/docs/stable/getting-started-with-charms-reactive
# for more information on this pattern.
from charms.reactive import main
main()
