#!/usr/bin/env python3

# Load modules from $JUJU_CHARM_DIR/lib
import os
import sys
sys.path.append('lib')

from charms.layer import basic
basic.bootstrap_charm_deps()

from charmhelpers.core.unitdata import kv
from charms.reactive import set_state
from charms.metering import CODE, INFO


if __name__ == '__main__':
    unit_data = kv()
    current = os.environ['JUJU_METER_STATUS']
    if current:
        current = str(current).lower()
        unit_data.set(CODE, current)
        unit_data.set(INFO, os.environ.get('JUJU_METER_INFO'))
    unit_data.flush(True)

    # This will load and run the appropriate @hook and other decorated
    # handlers from $JUJU_CHARM_DIR/reactive, $JUJU_CHARM_DIR/hooks/reactive,
    # and $JUJU_CHARM_DIR/hooks/relations.
    #
    # See https://jujucharms.com/docs/stable/authors-charm-building
    # for more information on this pattern.
    from charms.reactive import main_restricted
    main_restricted()

    unit_data.close()
