#!/usr/bin/env python3

# Load modules from $CHARM_DIR/lib
import os
import sys
sys.path.append('lib')

# This is an upgrade-charm context, make sure we install latest deps
os.unlink('wheelhouse/.bootstrapped')

from charms.bootstrap import bootstrap_charm_deps
bootstrap_charm_deps()


# This will load and run the appropriate @hook and other decorated
# handlers from $CHARM_DIR/reactive, $CHARM_DIR/hooks/reactive,
# and $CHARM_DIR/hooks/relations.
#
# See https://jujucharms.com/docs/stable/getting-started-with-charms-reactive
# for more information on this pattern.
from charms.reactive import main
main()
